name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  packages: write

env:
  BUILD_TYPE: Release
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
  USERNAME: Nunite
  FEED_URL: https://nuget.pkg.github.com/Nunite/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/Nunite/index.json,readwrite"

jobs:
  linux:
    name: Linux-x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
         
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.9.3'
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
          dir: '${{github.workspace}}/qt/'
          modules: 'qtshadertools'

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev ninja-build mono-complete
          
      - uses: lukka/get-cmake@latest
      
      - name: Restore artifacts, setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{env.VCPKG_ROOT}}'
          runVcpkgInstall: false
          vcpkgJsonIgnores: "['**/vcpkg/**', '**/vcpkg_config/**']"
         
      - name: Setup NuGet sources
        shell: bash
        env:
          VCPKG_EXE: ${{ env.VCPKG_ROOT }}/vcpkg
        run: |
          mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
            sources add \
            -Source "${{ env.FEED_URL }}" \
            -StorePasswordInClearText \
            -Name GitHubPackages \
            -UserName "${{ env.USERNAME }}" \
            -Password "${{ secrets.GITHUB_TOKEN }}"
          mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "${{ env.FEED_URL }}"

      - name: Configure
        run: >
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
      
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2
      
      - name: Prepare artifacts
        run: |
          mkdir "Half-Life Asset Manager"
          mv build/hlam "Half-Life Asset Manager"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x64
          path: "Half-Life Asset Manager"

  win64:
    name: Win64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.9.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          dir: '${{github.workspace}}/qt/'
          modules: 'qtshadertools'
      
      - uses: lukka/get-cmake@latest
      
      - name: Restore artifacts, setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{env.VCPKG_ROOT}}'
          runVcpkgInstall: false
          vcpkgJsonIgnores: "['**/vcpkg/**', '**/vcpkg_config/**']"
      
      - name: Setup NuGet sources
        shell: pwsh
        env:
          VCPKG_EXE: ${{ env.VCPKG_ROOT }}/vcpkg
        run: |
          & $(${{ env.VCPKG_EXE }} fetch nuget) `
            sources add `
            -Source "${{ env.FEED_URL }}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "${{ env.USERNAME }}" `
            -Password "${{ secrets.GITHUB_TOKEN }}"
          & $(${{ env.VCPKG_EXE }} fetch nuget) `
            setapikey "${{ secrets.GITHUB_TOKEN }}" `
            -Source "${{ env.FEED_URL }}"

      - name: Configure
        run: >
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -A x64
      
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2
      
      - name: Deploy Qt Dependencies
        shell: powershell
        run: |
          & "${{env.Qt6_DIR}}/bin/windeployqt.exe" --release --dir "${{github.workspace}}/build/deploy" "${{github.workspace}}/build/HLAM.exe"
          Copy-Item "${{github.workspace}}/build/HLAM.exe" -Destination "${{github.workspace}}/build/deploy"
          Copy-Item "${{github.workspace}}/build/OpenAL32.dll" -Destination "${{github.workspace}}/build/deploy"
          Copy-Item "${{github.workspace}}/build/fmt.dll" -Destination "${{github.workspace}}/build/deploy"

      - name: Prepare artifacts
        run: |
          mkdir "Half-Life Asset Manager"
          xcopy /E /I "build\deploy" "Half-Life Asset Manager"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Win64
          path: "Half-Life Asset Manager"
